app = "shitty-discord-trivia-bot"
primary_region = "arn"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024